pipeline {
    agent any

    stages {
        stage('pixel_mmp_healthcheck') {
                steps {
                     echo 'pixel_mmp_healthcheck..'
            script{
                try{
                    git branch: 'main', url: 'https://github.com/Bhavani2112/mmp_repo.git'
                    bat label: 'mmpbatchscript', script: 'mmphealthcheck.bat'
                  }
             
            catch(err) {
                  echo "pixel_mmp_healthcheck job failed"
                  echo "Caught: ${err}"
             }
            }
                }
        }
        stage('pixel_mmp_regtests') {
            steps {
			   echo 'Building Bhavani file..'
               git branch: 'main', url: 'https://github.com/Bhavani2112/mmp_repo.git'
               dir('mmppixel') 
               {
                           bat 'mvn clean test'
               }
            }
        }
    }
}